### ISSUE TITLE
Change alt= to title= in remote.xml?

### ISSUE THREAD

**Issue by prl001** [oe-alliance/branding-module#51]
Recent versions on Open Webif only use the `title=` attribute for their tool tip in the Open Webif, and the `alt=` attribute is ignored as tooltip text.

Should all remotes' remote.xml `<area/>` entries be changed to use `title=` for their tooltip text? If some other app uses `alt=`, shouldn't all remotes have both?

**Comment by AbuBaniaz** [comment]
It is unlikely someone would build an app against our version of OWIF, they would use the E2openplugins version.

Maybe we change it. If we break an app, we can duplicate alt and title or they change app. Really going to be impossible to check all apps.

I wonder what @jibyel suggests

**Comment by Huevos** [comment]
What do you mean our version?

https://github.com/oe-alliance/oe-alliance-core/blob/4.3/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-extensions-openwebif.bb#L33

**Comment by AbuBaniaz** [comment]
Issue closed. Was changed here

https://github.com/oe-alliance/branding-module/commit/3619e72a6f5b03293429cd5733981ee03043f9be#diff-144f3434bd1aa29214c65613a4bb3f76
