### ISSUE TITLE
Does the id= attribute have any purpose in remote.xml

### ISSUE THREAD

**Issue by prl001** [oe-alliance/branding-module#52]
If it doesn't, it should probably be removed from all remote.xml files.

If it does, it should probably be used in all remote.xml files.

**Comment by AbuBaniaz** [comment]
Changes made here: 

https://github.com/oe-alliance/branding-module/commit/5a3d6fc46073fa74dac928f98e8c5da7c50f944e

https://github.com/oe-alliance/branding-module/commit/1434d94d6177587ccb7b593489f7522db86a6353
